"Setting varibales
let mapleader=" "
let PMP=$PMP

"General
syntax enable
filetype plugin on
filetype indent on
set path+=**
set tags+=./.tags
set number
set nocompatible
set nostartofline
set ruler
set tabstop=4 softtabstop=4 expandtab shiftwidth=4 smarttab
set autoindent
set encoding=utf8
set linebreak
set scrolloff=8
set noerrorbells
set novisualbell
set title
set history=1000
set colorcolumn=150
set showmatch
set incsearch
set hlsearch
set ffs=unix,dos,mac
set termguicolors
set undofile

"Overrides vim path
set undodir=$PMP/vim/run/undo
set directory=$PMP/vim/run/swap
set backupdir=$PMP/vim/run/backup
set viewdir=$PMP/vim/run/view
set viminfo+='1000,n$PMP/vim/run/viminfo
set runtimepath=$PMP/run/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

"Autocompletion
set wildmenu
set wildmode=list:longest,full
set mouse=a

"Recomandations and checking for bash scripts
map <leader>s :!clear && shellcheck %<CR>

"Easy settings for wildmenu
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
inoremap <C-@> <C-n>

"Autocommands
autocmd FileType make setlocal noexpandtab
autocmd BufNewFile *.sh 0r $PMP/vim/skeletons/skeleton.sh
autocmd BufNewFile *.bash 0r $PMP/vim/skeletons/skeleton.bash
autocmd BufNewFile *.py 0r $PMP/vim/skeletons/skeleton.py
autocmd BufNewFile *.cpp 0r $PMP/vim/skeletons/skeleton.cpp
autocmd BufNewFile *.cc 0r $PMP/vim/skeletons/skeleton.cpp
autocmd BufNewFile *.hh 0r $PMP/vim/skeletons/skeleton.hh
autocmd BufNewFile *.tex 0r $PMP/vim/skeletons/skeleton.tex
autocmd BufNewFile *.rs 0r $PMP/vim/skeletons/skeleton.rs
autocmd BufWritePre * %s/\s\+$//e "Deletes all whitespaces at the end of the line
autocmd BufWritePost *.tex,*.zed :!pdflatex % &&  %:r.pdf &

"Jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

"Colorscheme
source $PMP/vim/theme/pmpTheme.vim "Need to source it because I don't want to interfere whith other colors

"Settings for statusLine
set laststatus=2
set statusline=
set statusline+=%1*\"%<%F\"\                        "File path, modified amd readonly
set statusline+=%3*│                                "|
set statusline+=%2*\ %Y\                            "File type
set statusline+=%3*│                                "|
set statusline+=%=                                  "Got to the right side
set statusline+=%2*\ col:\ %02v\                    "Col number
set statusline+=%1*\ ln:\ %02l/%L\ (%3p%%)\ %m%r    "Line number / total, percentage
