#!/bin/bash

function tree (){
    spaces=$((spaces+1))
    for file in `ls -A $1 | grep -v .git`; do
        for ((i=1;i<=$spaces;i++)); do
             printf "   "
        done
        echo $file
        [[ -d "$1/$file" ]] && tree $1/$file
    done
    spaces=$((spaces-1))
}

function call_tree (){
    spaces=0
    if [[ $1 == "" ]]; then
        $1="."
    fi
    echo $1
    tree $1
}
