#!/bin/bash
function completion_j () {
    COMPREPLY=()
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"
    possibilities=( $(sort -sgrt '|' $PMP/.cd | awk -F '|' '{ print $2 }' | sed -e 's/\ //g' -e 's/§/\\\ /g' -e '/^$/d' | awk -F '/' '{ print $NF }' | grep "$cur") )
    if [ "${#possibilities[@]}" -eq 1 ]; then
        COMPREPLY=$(compgen -W "${possibilities}" -- "${cur}")
    else
        echo 
        printf "\n${possibilities[*]}"
    fi
}
complete -F completion_j j
